# Generated by Django 2.2.12 on 2024-01-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airlines_id', models.IntegerField()),
                ('airlines_name', models.CharField(max_length=50)),
                ('airlines_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_id', models.IntegerField()),
                ('airport_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.IntegerField()),
                ('airlines', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('departure_airport', models.CharField(max_length=100)),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('arrival_airport', models.CharField(max_length=100)),
                ('max_seat', models.IntegerField(default=60)),
                ('bookead_seat', models.IntegerField()),
            ],
        ),
    ]
