# Generated by Django 2.2.12 on 2023-05-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='passenger_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
